// Chennai localities supported by the app. The schema field is still `city`
// for backward compatibility, but the values are Chennai locality names.
// To add/remove a locality: edit this list and the matching list in
// frontend/src/app/core/models/localities.ts, then redeploy both.
export const CHENNAI_LOCALITIES = [
  'Adambakkam',
  'Adyar',
  'Alandur',
  'Ambattur',
  'Aminjikarai',
  'Anna Nagar',
  'Arumbakkam',
  'Ashok Nagar',
  'Avadi',
  'Ayanavaram',
  'Besant Nagar',
  'Chetpet',
  'Choolaimedu',
  'Chromepet',
  'Egmore',
  'Ekkattuthangal',
  'George Town',
  'Guindy',
  'Injambakkam',
  'Kilpauk',
  'Kodambakkam',
  'Kolathur',
  'Korattur',
  'Kotturpuram',
  'Madhavaram',
  'Madipakkam',
  'Mandaveli',
  'Medavakkam',
  'Mogappair',
  'Mylapore',
  'Nanganallur',
  'Navalur',
  'Nungambakkam',
  'OMR (Old Mahabalipuram Road)',
  'Padi',
  'Pallavaram',
  'Pallikaranai',
  'Pammal',
  'Perambur',
  'Perumbakkam',
  'Perungudi',
  'Poonamallee',
  'Porur',
  'Purasawalkam',
  'Ramapuram',
  'Royapettah',
  'Royapuram',
  'Saidapet',
  'Selaiyur',
  'Sholinganallur',
  'Siruseri',
  'T. Nagar',
  'Tambaram',
  'Teynampet',
  'Thiruvanmiyur',
  'Thoraipakkam',
  'Tondiarpet',
  'Triplicane',
  'Vadapalani',
  'Valasaravakkam',
  'Vandalur',
  'Vanagaram',
  'Velachery',
  'Vepery',
  'Villivakkam',
  'Virugambakkam',
  'West Mambalam',
] as const;

export type ChennaiLocality = (typeof CHENNAI_LOCALITIES)[number];

export function isSupportedLocality(value: string): boolean {
  const v = value.trim().toLowerCase();
  return CHENNAI_LOCALITIES.some((c) => c.toLowerCase() === v);
}
