// Chennai localities for the locality dropdown. Keep in sync with
// backend/src/models/localities.ts. Schema field is still named `city`
// for backward compatibility.
export const CHENNAI_LOCALITIES = [
  'Adambakkam',
  'Adyar',
  'Alandur',
  'Ambattur',
  'Aminjikarai',
  'Anna Nagar',
  'Arumbakkam',
  'Ashok Nagar',
  'Avadi',
  'Ayanavaram',
  'Besant Nagar',
  'Chetpet',
  'Choolaimedu',
  'Chromepet',
  'Egmore',
  'Ekkattuthangal',
  'George Town',
  'Guindy',
  'Injambakkam',
  'Kilpauk',
  'Kodambakkam',
  'Kolathur',
  'Korattur',
  'Kotturpuram',
  'Madhavaram',
  'Madipakkam',
  'Mandaveli',
  'Medavakkam',
  'Mogappair',
  'Mylapore',
  'Nanganallur',
  'Navalur',
  'Nungambakkam',
  'OMR (Old Mahabalipuram Road)',
  'Padi',
  'Pallavaram',
  'Pallikaranai',
  'Pammal',
  'Perambur',
  'Perumbakkam',
  'Perungudi',
  'Poonamallee',
  'Porur',
  'Purasawalkam',
  'Ramapuram',
  'Royapettah',
  'Royapuram',
  'Saidapet',
  'Selaiyur',
  'Sholinganallur',
  'Siruseri',
  'T. Nagar',
  'Tambaram',
  'Teynampet',
  'Thiruvanmiyur',
  'Thoraipakkam',
  'Tondiarpet',
  'Triplicane',
  'Vadapalani',
  'Valasaravakkam',
  'Vandalur',
  'Vanagaram',
  'Velachery',
  'Vepery',
  'Villivakkam',
  'Virugambakkam',
  'West Mambalam',
] as const;

export type ChennaiLocality = (typeof CHENNAI_LOCALITIES)[number];
